cora:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-03
  weight_decay: 1.0e-04
  tau_g: 0.4
  tau_n: 0.9
  w_g: 0.3
  epochs: 200
  eval_lr: 0.001
  eval_epochs: 300
  dropout_rate: 0.4
  noise_std_n: 0.4
  noise_std_e: 0.01
  batch_size1: null
  batch_size2: null
  num_views: 2

citeseer:
  num_layers: 1
  hid_dim: 1024
  proj_dim: 1024
  lr: 1.0e-04
  weight_decay: 5.0e-04
  tau_g: 0.8
  tau_n: 0.9
  w_g: 0.5
  epochs: 150
  eval_lr: 0.001
  eval_epochs: 100
  dropout_rate: 0.9
  noise_std_n: 0.2
  noise_std_e: 0.01
  batch_size1: null
  batch_size2: null
  num_views: 2

pubmed:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 5.0e-04
  weight_decay: 1.0e-04
  tau_g: 0.8
  tau_n: 0.3
  w_g: 2.0
  epochs: 500
  eval_lr: 0.01
  eval_epochs: 300
  dropout_rate: 0.5
  noise_std_n: 0.1
  noise_std_e: 0.01
  batch_size1: null
  batch_size2: null
  num_views: 2

cora_coauthor:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-04
  weight_decay: 5.0e-04
  tau_g: 0.5
  tau_n: 0.7
  w_g: 1.0
  epochs: 300
  eval_lr: 0.001
  eval_epochs: 300
  dropout_rate: 0.3
  noise_std_n: 0.4
  noise_std_e: 0.01
  batch_size1: null
  batch_size2: null
  num_views: 2

dblp_coauthor:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-03
  weight_decay: 5.0e-04
  tau_g: 0.2
  tau_n: 0.9
  w_g: 1.0
  epochs: 300
  eval_lr: 0.01
  eval_epochs: 100
  dropout_rate: 0.5
  noise_std_n: 0.3
  noise_std_e: 0.0001
  batch_size1: 8192
  batch_size2: 4096
  num_views: 2

zoo:
  num_layers: 1
  hid_dim: 256
  proj_dim: 256
  lr: 1.0e-03
  weight_decay: 1.0e-04
  tau_g: 0.1
  tau_n: 0.2
  w_g: 0.5
  epochs: 100
  eval_lr: 0.005
  eval_epochs: 300
  dropout_rate: 0.0
  noise_std_n: 0.4
  noise_std_e: 0.0001
  batch_size1: null
  batch_size2: null
  num_views: 2

20newsW100:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-04
  weight_decay: 1.0e-03
  tau_g: 0.4
  tau_n: 0.8
  w_g: 0.5
  epochs: 150
  eval_lr: 0.01
  eval_epochs: 300
  dropout_rate: 0.4
  noise_std_n: 0.7
  noise_std_e: 0.001
  batch_size1: null
  batch_size2: null
  num_views: 2

Mushroom:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-03
  weight_decay: 5.0e-04
  tau_g: 0.1
  tau_n: 0.2
  w_g: 1.0
  epochs: 300
  eval_lr: 0.01
  eval_epochs: 300
  dropout_rate: 0.6
  noise_std_n: 0.4
  noise_std_e: 0.01
  batch_size1: null
  batch_size2: null
  num_views: 2

NTU2012:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 5.0e-04
  weight_decay: 5.0e-04
  tau_g: 0.4
  tau_n: 0.6
  w_g: 1.0
  epochs: 200
  eval_lr: 0.005
  eval_epochs: 100
  dropout_rate: 0.2
  noise_std_n: 0.1
  noise_std_e: 0.01
  batch_size1: null
  batch_size2: null
  num_views: 2

ModelNet40:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-03
  weight_decay: 5.0e-04
  tau_g: 0.4
  tau_n: 0.8
  w_g: 1.0
  epochs: 150
  eval_lr: 0.005
  eval_epochs: 300
  dropout_rate: 0.2
  noise_std_n: 0.1
  noise_std_e: 0.01
  batch_size1: null
  batch_size2: null
  num_views: 2
